spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      bootstrap-servers: kafka:9092
      group-id: pedido-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

  datasource:
    url: jdbc:postgresql://postgres:5432/gestrest-ms
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:gestrest-secret-key-for-jwt-tokens-very-long-and-secure}

gestrest:
  pagamento:
    service:
      url: http://gestrest-pagamento-service:8083/api/v1/pagamentos